### ISSUE TITLE
statsdbeat 7.1.2 ignores config

### ISSUE THREAD

**Issue by dbt4u** [sentient/statsdbeat#8]
We have configured as follow inside statsdbeat.yml (Using statsdbeat 7.1.2 against a ELS 7.4.2.):

```
index: statsd-%{[beat.version]}-%{+yyyy.MM.dd}

...

setup:
  template:
    name: statsd
    pattern: statsd-*
```

This would assume we would could create an index pattern in the form of "statsd-*"

But the resulting Index was for e.g. in the Form of:
statsdbeat-7.1.2-2020.11.25-000001

This breaks all our Visuals.

It seems work with a config on a 7.1.2 (beat) and 7.8.1 (ELS). Any Ideas?
